### ISSUE TITLE
Link Functional bean definition with Kotlin DSL (no reflection, no CGLIB proxies involved) in readme is broken

### ISSUE THREAD

**Issue by ofir-popowski** [sdeleuze/spring-kotlin-functional#1]
The link leads to https://github.com/sdeleuze/spring-kotlin-functional/blob/master/src/main/kotlin/micro/Beans.kt which gives 404. Maybe this is the right one ? https://github.com/sdeleuze/spring-kotlin-functional/blob/master/src/main/kotlin/functional/Beans.kt

Other links have the same problem: WebFlux functional routing declaration with Kotlin DSL and Junit 5 @BeforeAll and @AfterAll on non-static methods in Kotlin

**Comment by sdeleuze** [comment]
Fixed via https://github.com/sdeleuze/spring-kotlin-functional/commit/0a7fea5c4e608b9ae4a0ac9cb58fa1fdb56ed32a, thanks for reporting the problem.
