### ISSUE TITLE
CORS configuration

### ISSUE THREAD

**Issue by maistrovyi** [sdeleuze/spring-kotlin-functional#3]
Hey @sdeleuze, thank you for cool project.
I have question about CORS in your Netty configuration by Kotlin DSL - could you add CORS filter in project?

Thanks

**Comment by lucasvsme** [comment]
@maystrovyy Not sure if it's what you are looking for, but you can use the `filter()` method of `WebHttpHandlerBuilder`.

```kotlin
// Application.kt (line 27)

httpHandler = WebHttpHandlerBuilder
	.applicationContext(context)
	.filter(CrossOriginFilter())
	.build()
```

```kotlin
// CrossOriginFilter.kt

class CrossOriginFilter : WebFilter {

    override fun filter(context: ServerWebExchange, chain: WebFilterChain): Mono<Void> {
        // Your CORS rules here
    }
}
```

**Comment by sdeleuze** [comment]
@lucasvalenteds There is a builtin `CorsWebFilter` ;-)

@maystrovyy I have added optional CORS support (enable `cors`  profile to make it active), see https://github.com/sdeleuze/spring-kotlin-functional/commit/4556da106c6d9733a9cc27d255b779c3a64235b2 (WebFlux standalone) or https://github.com/sdeleuze/spring-kotlin-functional/commit/e04503164f0fda9670762f7c355f551502d1e7a6 (Boot 2).
