### ISSUE TITLE
exception handler - example

### ISSUE THREAD

**Issue by cdimascio** [sdeleuze/spring-kotlin-functional#4]
@sdeleuze i'd like to register an exception handler that transforms an exception into a json response.

for example, I'd like to create a custom `WebExceptionHandler` that upon receiving an exception e.g. `Exception("oh snap! something went wrong")`, it return a json response e.g.
```
 {
   "code": "internal_server_error",
   "message": "oh snap something went wrong"
}
```

i see the default exception strategy does this

```
public Mono<Void> handle(ServerWebExchange exchange, Throwable ex) {
	if (ex instanceof ResponseStatusException) {
		exchange.getResponse().setStatusCode(((ResponseStatusException) ex).getStatus());
		logger.debug(ex.getMessage());
		return exchange.getResponse().setComplete();
	}
	return Mono.error(ex);
}
```

All in all, its not clear to me how to respond with json from the exception handler. It seems like i must transform the exception into a `DataBuffer`, however this seems fairly complicated.

Any ideas? An example would be greatly appreciated!

Also, thanks so much for this example project. I've found it super helpful.

**Comment by cdimascio** [comment]
@sdeleuze if you're interested, i put together a sample template app here

https://github.com/cdimascio/kotlin-swagger-spring-functional-template

I ended up handling errors in the handler function. its actually relatively clean
e.g.

```kotlin

fun create(req: ServerRequest) = validate
        .request(req)
        .withBody(User::class.java) { body -> ok().body(Mono.just(body)) }
        .onErrorResume { t-> internalServerError(t) }
}

```

**Comment by cdimascio** [comment]
Closing this out. I found a solution using a filter on the route function

**Comment by sdeleuze** [comment]
Sorry not sure why but I missed the notifications for your original messages. Glad you find the solution.
