### ISSUE TITLE
build.gradle.kts all red

### ISSUE THREAD

**Issue by JiangGuangxing** [sdeleuze/spring-kotlin-functional#5]
I download this code,and the build.gradle.kts file was all red ,idea prompt unresolved reference:kotlin,can you tell me why,thank you !

**Comment by JiangGuangxing** [comment]
Look forward to your recovery,thank you

**Comment by JiangGuangxing** [comment]
I update my local gradle to 4.4.1,and this question is solved

**Comment by sdeleuze** [comment]
Ok so I close this issue.
